"""update tables

Revision ID: 0ad804066c04
Revises: 2226cf6e1f1d
Create Date: 2025-11-17 16:05:49.577566

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ad804066c04"
down_revision: Union[str, Sequence[str], None] = "2226cf6e1f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("transaction", "created")
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("user", "created")
    op.add_column("user_balance", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("user_balance", "created")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_balance",
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_column("user_balance", "created_at")
    op.add_column(
        "user",
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_column("user", "created_at")
    op.add_column(
        "transaction",
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("transaction", "created_at")
    # ### end Alembic commands ###
