"""update column from created_at to created

Revision ID: 5cf91346238c
Revises: 0ad804066c04
Create Date: 2025-11-17 16:08:22.793472

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5cf91346238c"
down_revision: Union[str, Sequence[str], None] = "0ad804066c04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("created", sa.DateTime(), nullable=False))
    op.drop_column("transaction", "created_at")
    op.add_column("user", sa.Column("created", sa.DateTime(), nullable=False))
    op.drop_column("user", "created_at")
    op.add_column("user_balance", sa.Column("created", sa.DateTime(), nullable=False))
    op.drop_column("user_balance", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_balance",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user_balance", "created")
    op.add_column(
        "user",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user", "created")
    op.add_column(
        "transaction",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("transaction", "created")
    # ### end Alembic commands ###
