"""add column 'updated_at' and rename column from 'created' to 'created_at'

Revision ID: c4316b7e629d
Revises: 5cf91346238c
Create Date: 2025-11-17 17:35:34.458375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4316b7e629d"
down_revision: Union[str, Sequence[str], None] = "5cf91346238c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("transaction", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("transaction", "created")
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("user", "created")
    op.add_column("user_balance", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user_balance", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("user_balance", "created")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_balance",
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("user_balance", "updated_at")
    op.drop_column("user_balance", "created_at")
    op.add_column(
        "user",
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.add_column(
        "transaction",
        sa.Column("created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("transaction", "updated_at")
    op.drop_column("transaction", "created_at")
    # ### end Alembic commands ###
